### ISSUE TITLE
Tema 4 exercism

### ISSUE THREAD

**Issue by leonistor** [vladistr08/moni_time#3]
Triangle
Rational Numbers
Secret Handshake
Rational Numbers
Darts

**Comment by vladistr08** [comment]
La problema Secret Handshake m-am chinuit putin sa caut pe net si mi-am adus aminte cum ai rezolvat problema cu alergiile de data trecuta si pana la urma am reusit sa o fac, dar daca mai gasesti as mai vrea probleme de genu pana le prind.
